#ifdef PRT_USE_GC
#include <gc.h>
#endif // PRT_USE_GC

// The main function generated by the compiler.
extern void __ppurs_main();

int main() {
#ifdef PRT_USE_GC
  GC_INIT();
  GC_enable_incremental();
#endif // PRT_USE_GC

  __ppurs_main();
  return 0;
}
